### PR TITLE
Fix GET meals endpoint to show meal foods

### LINKED ISSUE #41: Developer: Fix GET meals endpoint
The meals endpoint should send back not only a list of meals in the database, but also the associated foods for each meal. This latter point needs to be implemented.

### PR DESCRIPTION
**Pull request by DanHutch**
## Type of change
____  New feature
__x__  Bug Fix
____  Refactor

# Description
Implements changes/fix for GET /meals endpoint. New functionality sends API response with food objects included, where relevant meal_foods exist, within the "foods" property of each meal. 
@geoffreyadebonojo please review. Thanks!
closes #41 

# Code Check
- [x] Wrote Tests
- [x] Implemented
- [ ] Reviewed (by Someone Else)

# Functionality
- [x] All Tests are Passing
- [x] The code will run locally
- [x] This broke nothing
- [x] The code is fully tested (greater than 98% coverage)
- [] There is no unused/commented out code

# Testing Changes
____ No Tests have been changed
__x__ Some Tests have been changed
____ All of the Tests have been changed(Please describe what in the world happened)

### CODE REVIEW

File: index.js [hunk 1]
```diff
@@ -109,9 +109,26 @@ app.get('/api/v1/days', (request, response) => {
 });
 
 app.get('/api/v1/meals', (request, response) => {
-  database('meals').select()
+  database('meals').leftJoin('meal_foods', 'meals.id', '=', 'meal_foods.meal_id', 'foods.').leftJoin('foods', 'meal_foods.food_id', '=', 'foods.id').select("meals.id AS id", "meal_type AS name", "name AS food", "calories AS calories", "foods.id AS food_id").groupBy('meals.id', "foods.name", "foods.calories", "foods.id").orderBy('meals.id')
   .then((meals) => {
-    response.status(200).json(meals);
+    let newMeals = meals.reduce((acc, meal, _, src) => {
```
Comment (geoffreyadebonojo) [inline index.js]: Great work putting this together

**Comment by geoffreyadebonojo** [comment]
Great work. Let's meet up and walk through the changes.
